# HW:
- почитать документацию про NumPy и создать примеры тех функций которые мы не успели рассмотреть на занятиях
- придумать свои примеры

In [2]:
import numpy as np

In [3]:
# NumPy Arrays, dtypes, and shapes
a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a.dtype)

[1 2 3]
(3,)
int32


In [4]:
b = np.array([[0, 2, 4], [1, 3, 5]])
print(b)
print(b.shape)
print(b.dtype)

[[0 2 4]
 [1 3 5]]
(2, 3)
int32


In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(shape=(3, 4), dtype=np.int32)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
# Общие операции с массивами
c = b * 0.5
print(c)
print(c.shape)
print(c.dtype)

[[0.  1.  2. ]
 [0.5 1.5 2.5]]
(2, 3)
float64


In [9]:
d = a + c
print(d)

[[1.  3.  5. ]
 [1.5 3.5 5.5]]


In [10]:
d[0]

array([1., 3., 5.])

In [11]:
d[0, 0]

1.0

In [12]:
d[:, 0]

array([1. , 1.5])

In [30]:

print(d.sum())
print(d.mean())
print(d.sum(axis=0))
print(d.sort() )
print(d.argmax()) # Returns the index of the maximal element
print(d.cumsum()) # Cumulative sum of the elements
print(d.cumprod()) # Cumulative product of the elements
print(d.var()) # Variance
print(d.std()) # Standard deviation


19.5
3.25
[ 2.5  6.5 10.5]
None
5
[ 1.   4.   9.  10.5 14.  19.5]
[  1.      3.     15.     22.5    78.75  433.125]
2.7291666666666665
1.6520189667999174


In [32]:
# Если z — неубывающий массив, то z.searchsorted(a) возвращает индекс первого элемента z, который >= a
z = np.linspace(2, 4, 5)
print(z)
print(z.searchsorted(2.2))

[2.  2.5 3.  3.5 4. ]
1


In [34]:
# NumPy предоставляет версии стандартных функций
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [33]:
# Копирование 
a = np.random.randn(3)
print(a)
b = np.copy(a)
print(b)


[-2.29465101  0.63329149  0.17697098]
[-2.29465101  0.63329149  0.17697098]


In [35]:
# Функция NumPy np.where предоставляет векторизованную альтернативу:
x = np.random.randn(4)
print(x)
print(np.where(x > 0, 1, 0))  # Insert 1 if x > 0 true, otherwise 0

[-0.34945549 -0.8667024  -0.90543969 -1.05640656]
[0 0 0 0]


In [36]:
# Генерация значений 
z = np.random.randn(10000)  # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000)    # 1,000 draws from Bin(10, 0.5)
y.mean()

5.017

In [39]:
# Детерменант матрицы и обратная матрица
A = np.array([[1, 2], [3, 4]])
print(np.linalg.det(A))
print(np.linalg.inv(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
# изменение размеров 
e = np.arange(12)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
f = e.reshape(3, 4)
print(f)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
e[5:] = 0
print(e)

[0 1 2 3 4 0 0 0 0 0 0 0]


In [21]:
f

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
f.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [ ]:
# Объединение массивов 

In [23]:
a

array([1, 2, 3])

In [24]:
b

array([[0, 2, 4],
       [1, 3, 5]])

In [25]:
d

array([[1. , 3. , 5. ],
       [1.5, 3.5, 5.5]])

In [26]:
# последовательно объединение
np.concatenate([a, a, a])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
# вставка по вертикальной оси
np.vstack([a, b, d])

array([[1. , 2. , 3. ],
       [0. , 2. , 4. ],
       [1. , 3. , 5. ],
       [1. , 3. , 5. ],
       [1.5, 3.5, 5.5]])

In [29]:
# вставка по горизонтальной оси 
np.hstack([b, d])

array([[0. , 2. , 4. , 1. , 3. , 5. ],
       [1. , 3. , 5. , 1.5, 3.5, 5.5]])